apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-frontend-configmap
  namespace: expense-nm
  labels: 
    app: frontend
    module: frontend
    project: expense
data:
  
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-nm
  labels:
    app: frontend
    module: frontend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      module: frontend
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        module: frontend
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: expense-frontend-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: expense-nm
  labels:
    app: frontend
    module: frontend
    project: expense
spec:
  ports:
  - name: frontend
    protocol: TCP
    port: 8080
    targetPort: 8080
