apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-backend-configmap
  namespace: expense-nm
  labels: 
    app: backend
    module: backend
    project: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-nm
  labels:
    app: backend
    module: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      module: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        module: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: naresh34/backend:v1
        envFrom:
        - configMapRef:
            name: expense-backend-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: expense-nm
  labels:
    app: backend
    module: backend
    project: expense
spec:
  selector: 
    app: backend
    module: backend
    project: expense
  ports:
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080
