apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense-nm
  labels:
    app: mysql
    module: db
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      module: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        module: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: expense-service
#   namespace: expense-nm
#   labels: 
#     app: mysql
#     module: db
#     project: expense
# spec:
#   ports:
#   - name: mysql-svc
#     protocol: TCP
#     port: 3306
#     targetPort: 3306    