apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense-nm
  labels:
    app: mysql
    module: db
    project: expense
spec:
  replicas: 
  selector:
    matchLabels:
      app: mysql
      module: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        module: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: naresh34/mysql:v1
        ports:
        - containerPort: 3306
